/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfacez;

import buffete.MYSQLConexion;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jared
 */
public class Clientes extends javax.swing.JInternalFrame {
MYSQLConexion cc = new MYSQLConexion();
Connection con = cc.conexion();
String ID ;
    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
        mostrardatos();
//        llenarcombo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        paterno = new javax.swing.JTextField();
        materno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rfc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        curp = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        facebook = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Clientes");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 510, 220));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Paterno");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 70, -1));
        jPanel1.add(paterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 110, -1));
        jPanel1.add(materno, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 100, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Materno");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 80, -1));
        jPanel1.add(rfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 100, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Buscar por id");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));
        jPanel1.add(curp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 100, -1));

        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        jPanel1.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 110, -1));
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 100, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Telefono");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 80, -1));

        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/003-add 1.png"))); // NOI18N
        jButton1.setText("Registrar");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 120, -1));

        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/045-third quarter 1.png"))); // NOI18N
        jButton2.setText("Buscar");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 120, -1));

        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/016-delete 1.png"))); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 120, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Curp");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 50, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Email");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 50, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Nombre");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 70, -1));
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 100, -1));
        jPanel1.add(facebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 110, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Facebook");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 80, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Registro de Clientes");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        jPanel1.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 100, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("RFC");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 40, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 590, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       RegistrarClientes();
       RegistrarContacto(); 
       RegistrarFB();
        RegistrarMail();
         RegistrarTelefono();
         
         clean();
        if (facebook.getText().length() > 0 ){
            
        } else{
        } if (mail.getText().length() > 0){
         
        }else{
        } if(telefono.getText().length() > 0){
      
        }else{ 
        } 
    }//GEN-LAST:event_jButton1ActionPerformed
        
    public void buscarfb(){
    int resultado = 0;
    String fb;
        try {
            String nomb = jTextFieldName.getText(); 
           String sql = ("SELECT co.usuario FROM facebook co, contacto cn, cliente cl WHERE cn.id_contacto = co.id_contacto AND  cn.id_cliente ='" + nomb + "' GROUP BY usuario;");
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery(sql);
           
            if (rs.next()) {
                resultado = 1;
                fb = rs.getString("usuario");
               
                if (resultado == 1) {
               facebook.setText(fb);
                
            }
            } 
        } catch (Exception e) {
        }
    }
    public void buscarmail(){
    int resultado = 0;
    String ml;
        try {
            String nomb = jTextFieldName.getText().trim(); 
           String sql = ("SELECT co.cuenta FROM correo co, contacto cn, cliente cl WHERE cn.id_contacto = co.id_contacto AND  cn.id_cliente ='"+ nomb +"' GROUP BY cuenta");
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery(sql);
           
            if (rs.next()) {
                resultado = 1;
                ml = rs.getString("cuenta");
               
                if (resultado == 1) {
               mail.setText(ml);
                
            }
            } 
        } catch (Exception e) {
        }
    }
    public void buscarphone(){
    int resultado = 0;
    String phone;
        try {
            String nomb = jTextFieldName.getText(); 
           String sql = ("SELECT co.numero FROM telefono co, contacto cn, cliente cl WHERE cn.id_contacto = co.id_contacto AND  cn.id_cliente = '"+nomb+"' GROUP BY numero;");
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery(sql);
           
            if (rs.next()) {
                resultado = 1;
                phone = rs.getString("numero");
               
                if (resultado == 1) {
               telefono.setText(phone);
                
            }
            } 
        } catch (Exception e) {
        }
    }
    public  void busqueda(){
    
        int rst = 0;
        String idcliente;
        String  patern;
       String matern;
       String cedule; 
       String RFC;
       String n;
      
       try {
           
           String nomb = jTextFieldName.getText(); 
           String sql = ("SELECT * FROM cliente" + " WHERE id_cliente='" + nomb + "'");
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery(sql);
           
           if (rs.next()) {
               rst = 1;
//               idcliente = rs.getString("id_cliente");
               n = rs.getString("nombre");
               patern = rs.getString("paterno");
               matern = rs.getString("materno");
               cedule = rs.getString("CURP");
               RFC = rs.getString("RFC");
               
               if(rst == 1){
                   JOptionPane.showMessageDialog(null, "Registro Encontrado");
                   nombre.setText(n);
                   paterno.setText(patern);
                   materno.setText(matern);
                   curp.setText(cedule);
                   rfc.setText(RFC);
                  
                   
               }else{
               
               }
               
               
               
           } else {
          JOptionPane.showMessageDialog(null, "Regitro No Encontrado");
           }
           if (facebook.getText().length() > 0){
               facebook.setText("");
           }
            
           
       } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
       
       
        
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        busqueda();
        buscarfb();
        buscarmail();
        buscarphone();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DeleteClientes();
    }//GEN-LAST:event_jButton3ActionPerformed

//  public void llenarcombo(){
//      
//     MYSQLConexion.conexion();
//        ArrayList<String> medios = new ArrayList<String>();
//        medios = MYSQLConexion.Medios();
//       for (int i = 0; i < medios.size(); i++){
//           jComboBox1.addItem(medios.get(i));
//       }
//
//        }
  
    
      public void clean(){
            nombre.setText("");
            paterno.setText("");
            materno.setText("");
            facebook.setText("");
            rfc.setText("");
            mail.setText("");
            telefono.setText("");
            curp.setText("");
            
    }
    
    
    public void mostrardatos(){
    
      DefaultTableModel Tabgdo = new DefaultTableModel();
      Tabgdo.addColumn("Id_cliente");
      Tabgdo.addColumn("Nombre");
      Tabgdo.addColumn("Paterno");
      Tabgdo.addColumn("Materno");
      Tabgdo.addColumn("RFC");
      Tabgdo.addColumn("Curp");
      jTable1.setModel(Tabgdo);    
      String []clientes = new String[6];
      try {
            String sql = ("SELECT * from cliente");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
           while(rs.next()){
              clientes[0] = rs.getString("id_cliente");
               clientes[1] = rs.getString("nombre");
               clientes[2] = rs.getString("paterno");
               clientes[3] = rs.getString("materno");
               clientes[4] = rs.getString("rfc");
               clientes[5] = rs.getString("curp");
               Tabgdo.addRow(clientes);
           }
           
           
           jTable1.setModel(Tabgdo);
      } catch (HeadlessException | SQLException e) {
          JOptionPane.showMessageDialog(null, e);
      }
      
      
  
  }
  
  public void RegistrarContacto(){
      
      try {
          String SQL = "SELECT id_cliente FROM cliente ORDER BY id_cliente DESC LIMIT 1";
          Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            if(rs.next()) {              
             ID = rs.getString("id_cliente");
              PreparedStatement Conc = con.prepareStatement("INSERT INTO contacto (id_cliente) VALUES (?)");
            Conc.setString(1, ID);
            Conc.executeUpdate();
          } else{}
          
           
            
      } catch (Exception e) {
      }
  }
  public void RegistrarFB(){
            try {      
            String idcl = ID;
            String SQL = "SELECT id_contacto  FROM contacto "
                    + "WHERE  id_cliente='"+ idcl +"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            String idr;
            if (rs.next()) {
            idr = rs.getString("id_contacto");
            PreparedStatement fb = con.prepareStatement("INSERT INTO facebook (id_contacto, usuario) VALUES (?,?)");
             fb.setString(1, idr);
            fb.setString(2, facebook.getText().trim());
            fb.executeUpdate();
                
      
            } else {
                
            }
           
            } catch (Exception e) {
            }
}
  public void RegistrarTelefono(){
       try {
           String idcl = ID;
            String SQL = "SELECT id_contacto FROM contacto "
                    + "WHERE  id_cliente='"+ idcl +"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            String idr;
            if (rs.next()) {
            idr = rs.getString("id_contacto");
            PreparedStatement Tl = con.prepareStatement("INSERT INTO telefono (id_contacto, numero) VALUES (?,?)");
             Tl.setString(1, idr);
            Tl.setString(2, telefono.getText().trim());
           Tl.executeUpdate();
                
            } else {
                
            }
      } catch (Exception e) {
      }
  }
  public void RegistrarMail(){
      try {
           String idcl = ID;
            String SQL = "SELECT id_contacto  FROM contacto "
                    + "WHERE  id_cliente='"+ idcl +"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            String idr;
            if (rs.next()) {
            idr = rs.getString("id_contacto");
            PreparedStatement ml = con.prepareStatement("INSERT INTO correo (id_contacto, cuenta) VALUES (?,?)");
             ml.setString(1, idr);
            ml.setString(2, mail.getText().trim());
            ml.executeUpdate();
                
      
            } else {
                
            }
      } catch (Exception e) {
      }
  }
   public void RegistrarClientes(){
        try {

            PreparedStatement pst = con.prepareStatement("INSERT INTO cliente ( nombre, paterno, materno, curp, rfc ) VALUES (?,?,?,?,?)");
//            pst.setString(1, id.getText().trim());
            pst.setString(1, nombre.getText().trim());
            pst.setString(2, paterno.getText().trim());
            pst.setString(3, materno.getText().trim());
            pst.setString(4, curp.getText().trim());
            pst.setString(5, rfc.getText().trim());
            pst.executeUpdate();

//            clean();
              JOptionPane.showMessageDialog(null, "Cliente Regisrado con exito!");

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        mostrardatos();
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField curp;
    private javax.swing.JTextField facebook;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField materno;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField paterno;
    private javax.swing.JTextField rfc;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables

    private void DeleteClientes() {
         try {
            MYSQLConexion conex = new MYSQLConexion();
            conex.conexion();
            String ide = jTable1.getValueAt(jTable1.getSelectedRow(),0).toString();
            String slq = "DELETE FROM cliente WHERE id_cliente='" + ide +"'";
            
            
           conex.sentencia.execute(slq);
           
           
           
           JOptionPane.showMessageDialog(null, "Registro Eliminado");

        } catch (Exception e) {
        }
    }
}
