/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfacez;

import buffete.Abogatos;
import buffete.MYSQLConexion;
import buffete.TAsuntos;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jared
 */
public class Prefiere extends javax.swing.JInternalFrame {
MYSQLConexion cc = new MYSQLConexion();
Connection con = cc.conexion();
    /**
     * Creates new form Prefiere
     */
    public Prefiere() {
        initComponents();
        llenarcombox();
        mostrar();
    }
    public void mostrar(){
       DefaultTableModel data = new DefaultTableModel();
        data.addColumn("Abogado");
        data.addColumn("Tipo Asunto");
        jTable1.setModel(data);
        
        String []datos = new String[2];
        
        try {
           
            String sql = ("SELECT a.nombre as nombre , asu.descripcion as descripcion from abogado a, tipo_asunto asu, prefiere pe WHERE pe.id_abogado = a.id_abogado AND pe.id_tipo_asu = asu.id_tipo_asunto");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()) {                
                 datos[0] = rs.getString("nombre");
                datos[1] = rs.getString("descripcion");
            data.addRow(datos);
   
                
            }
            
            jTable1.setModel(data);
    } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
    
    
   
    
    }
    
    public void registrar(){
        try {
            PreparedStatement pst = con.prepareStatement("INSERT prefiere (id_abogado,id_tipo_asu ) VALUES (?,?)");
            pst.setString(1, Integer.toString(jComboBoxAbogado.getItemAt(jComboBoxAbogado.getSelectedIndex()).getId()));
            pst.setString(2, Integer.toString(jComboBoxTipoAsunto.getItemAt(jComboBoxTipoAsunto.getSelectedIndex()).getId()));
            pst.executeUpdate();
        } catch (Exception e) {
        }
        mostrar();
    
    }
    
    public void llenarcombox(){
         MYSQLConexion Abogadoss = new MYSQLConexion();
        ArrayList<Abogatos> abogados = Abogadoss.Abogado();
        for (int i = 0; i < abogados.size(); i++) {
            jComboBoxAbogado.addItem(
            new Abogatos(abogados.get(i).getId(), abogados.get(i).getNombre())
            );
            
            
    }
        
        MYSQLConexion Tipos_Asuntos = new MYSQLConexion();
        ArrayList<TAsuntos> asuntos = Tipos_Asuntos.Asuntos();
        for (int i = 0; i < asuntos.size(); i++) {
            jComboBoxTipoAsunto.addItem(
            new TAsuntos(asuntos.get(i).getId(), asuntos.get(i).getDescripcion())
            );
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxAbogado = new javax.swing.JComboBox<>();
        jComboBoxTipoAsunto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Preferencias");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Prefencias");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel1.add(jComboBoxAbogado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 130, 40));

        jPanel1.add(jComboBoxTipoAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 120, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID Tipo Asunto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ID Abogado");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 550, 140));

        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/003-add 1.png"))); // NOI18N
        jButton4.setText("Registrar");
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        registrar();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<Abogatos> jComboBoxAbogado;
    private javax.swing.JComboBox<TAsuntos> jComboBoxTipoAsunto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
